name: Robot Framework CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  robot-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Run Robot Framework Tests
      run: |
        robot test_calc.robot

    - name: Upload Robot Report
      uses: actions/upload-artifact@v4
      with:
        name: robot-report
        path: |
          output.xml
          log.html
          report.html